Gallery/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Gallery.Models.PictureViewModels;
using GalleryServices.ServicesInterfaces;
using GalleryStorage.Models;
using Microsoft.AspNetCore.Mvc;

namespace Gallery.Controllers
{
    public class PictureController : BaseController
    {
        private readonly IAlbumServices<Album> _albumServices;
        private readonly IPictureServices<Picture> _pictureServices;
        private readonly ITagServices<Tag> _tagServices;
        private readonly IEmailServices _emailServices;

        public PictureController(IAlbumServices<Album> albumServices, IPictureServices<Picture> pictureServices, 
            IUserServices<User> userServices, ITagServices<Tag> tagServices, IEmailServices emailServices)
                : base(userServices)
        {
            _albumServices = albumServices;
            _pictureServices = pictureServices;
            _userServices = userServices;
            _tagServices = tagServices;
            _emailServices = emailServices;
        }


        public IActionResult AddPicture(Guid albumId)
        {
            AddingPictureViewModel model = new AddingPictureViewModel() { AlbumId = albumId };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddPicture(AddingPictureViewModel pictureViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(pictureViewModel);
            }

            List<string> tagNames = pictureViewModel.Tags.Split(',').ToList();
            for (int i = 0; i < tagNames.Count; i++)
            {
                tagNames[i] = tagNames[i].Trim();
            }

            List<Tag> tags = new List<Tag>();
            foreach (var tagName in tagNames)
            {
                Tag tag = (await _tagServices.GetByNameAsync(tagName));
                if (tag == null)
                {
                    tag = new Tag { Name = tagName };
                    await _tagServices.AddAsync(tag);
                }
                tags.Add(tag);
            }

            Album album = await _albumServices.GetAsync(pictureViewModel.AlbumId);

            Picture picture = new Picture
            {
                Name = pictureViewModel.Name,
                Description = pictureViewModel.Description,
                FileName = pictureViewModel.Picture.FileName,
                PostDateTime = DateTime.Now,
                UserId = album.UserId,
                Album = album
            };
            picture.FileName = picture.Id + Path.GetExtension(pictureViewModel.Picture.FileName);
            await _pictureServices.AddAsync(picture);

            foreach (var tag in tags)
            {
                picture.PictureTags.Add(new PictureTag { PictureId = picture.Id, TagId = tag.Id});
            }
            await _pictureServices.UpdateAsync(picture);

            try
            {
                using (var fileStream = new FileStream(_pictureServices.GetFullPath(picture), FileMode.Create))
                {
                    await pictureViewModel.Picture.CopyToAsync(fileStream);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return RedirectToAction("Album", "Album", new { albumId = album.Id });
            }

            _pictureServices.CreateThumbnail(picture);

            return RedirectToAction("Album", "Album", new { albumId = album.Id });
        }

        [HttpPost]
        public async Task<IActionResult> DeletePicture(Guid pictureId)
        {
            Album album = (await _pictureServices.GetAsync(pictureId)).Album;
            if (!(await IsAdminOrCurrentUser(album.User)))
            {
                return StatusCode(401);
            }
            await _pictureServices.DeleteAsync(await _pictureServices.GetAsync(pictureId));

            return RedirectToAction("Album", "Album", new { albumId = album.Id });
        }

        [HttpGet]
        public async Task<IActionResult> DeletePictureForReason(Guid pictureId)
        {
            Picture picture = await _pictureServices.GetAsync(pictureId);
            PictureViewModel pictureViewModel = Mapper.Map<Picture, PictureViewModel>(picture);
            pictureViewModel.RelativePath = _pictureServices.GetRelativePath(picture);

            return View(pictureViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePictureForReason(Guid pictureId, string reason)
        {
            if (!User.IsInRole("admin"))
            {
                return StatusCode(401);
            }

            Picture picture = await _pictureServices.GetAsync(pictureId);
            User user = await _userServices.FindByIdAsync(picture.UserId);
            await _emailServices.SendEmailAsync(user.Email, "Message from Gallery administration",
                $"Your work \"{picture.Name}\" was deleted for reason: {reason}");

            Album album = (await _pictureServices.GetAsync(pictureId)).Album;
            await _pictureServices.DeleteAsync(picture);

            return RedirectToAction("Album", "Album", new { albumId = album.Id });
        }

        public async Task<IActionResult> ViewPictureInFullSize(Guid pictureId)
        {
            Picture picture = await _pictureServices.GetAsync(pictureId);
            PictureViewModel pictureViewModel = Mapper.Map<Picture, PictureViewModel>(picture);
            pictureViewModel.RelativePath = _pictureServices.GetRelativePath(picture);
            foreach (var commentViewModel in pictureViewModel.Comments)
            {
                User user = await _userServices.FindByIdAsync(commentViewModel.UserId);
                if (user != null)
                {
                    commentViewModel.UserPseudonym = user.Pseudonym;
                }
                else
                {
                    commentViewModel.UserPseudonym = "Deleted user";
                }
            }

            ViewBag.UserIsAuthenticated = User.Identity.IsAuthenticated;
            ViewBag.IsAdmin = CurrentUserIsAdmin();
            ViewBag.CurrentUserId = await CurrentUserId();
            ViewBag.OwnerId = picture.UserId;
            ViewBag.OwnerPseudonym = (await _userServices.FindByIdAsync(picture.UserId)).Pseudonym;

            Album album = await _albumServices.GetAsync(picture.AlbumId);
            var pictures = album.Pictures.OrderByDescending(x => x.PostDateTime).ToList();
            var indexOfPicture = pictures.IndexOf(picture);

            ViewBag.NextPictureId = indexOfPicture == 0 ? pictures.Last().Id : pictures.ElementAt(indexOfPicture - 1).Id;
            ViewBag.PreviousPictureId = indexOfPicture == (pictures.Count() - 1) ? pictures.First().Id : pictures.ElementAt(indexOfPicture + 1).Id;
            return View(pictureViewModel);
        }

        public async Task<JsonResult> GetPictureRating(Guid pictureId)
        {
            Picture picture = await _pictureServices.GetAsync(pictureId);
            return Json(new { value = picture.Ratings.Count });
        }
    }
}

Gallery/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using Gallery.Models.PictureViewModels;
using GalleryStorage.Models;
using Gallery.Models.UserManagingViewModels;
using Gallery.Sorting;
using Gallery.Pager;
using GalleryServices.ServicesInterfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;

namespace Gallery.Controllers
{
    public class UsersController : BaseController
    {
        private readonly IConfiguration _configuration;
        private readonly ISignInServices<User> _signInServices;
        private readonly IPictureServices<Picture> _pictureServices;
        private readonly int _picturesOnPage;

        public UsersController(IConfiguration configuration, IUserServices<User> userServices, ISignInServices<User> signInServices, IPictureServices<Picture> pictureServices)
            : base(userServices)
        {
            _configuration = configuration;
            _picturesOnPage = Int32.TryParse(_configuration["PicturesOnPage:Default"], out _picturesOnPage) ? Int32.Parse(_configuration["PicturesOnPage:Default"]) : 16;
            _userServices = userServices;
            _signInServices = signInServices;
            _pictureServices = pictureServices;
        }


        public async Task<IActionResult> GetUserPicturesPage(Guid userId, int? page, PictureSortState? sortOrder)
        {
            User user = await _userServices.FindByIdAsync(userId);
            List<Picture> userPictures = new List<Picture>();
            foreach (var album in user.Albums)
            {
                userPictures.AddRange(album.Pictures);
            }

            int pageNumber = page ?? 1;
            if (pageNumber == 0)
            {
                pageNumber = 1;
            }
            PictureSortState order = sortOrder ?? PictureSortState.PostDateTimeDesc;

            PictureSorter sorter = new PictureSorter
            {
                Pictures = userPictures.AsQueryable(),
                SortOrder = order
            };

            Pager<Picture> pager = new Pager<Picture>();
            pager.SetRecordsOnPage(_picturesOnPage);
            var picturesForPager = sorter.Sort().ToList();
            pager.SetRecords(picturesForPager);

            List<PictureViewModel> pictureViewModels = new List<PictureViewModel>();
            foreach (var picture in pager.GetPage(pageNumber))
            {
                PictureViewModel pictureViewModel = Mapper.Map<Picture, PictureViewModel>(picture);
                pictureViewModel.ThumbnailRelativePath = _pictureServices.GetThumbnailRelativePath(await _pictureServices.GetAsync(picture.Id));
                pictureViewModels.Add(pictureViewModel);
            }

            PictureSearchViewModel model = new PictureSearchViewModel
            {
                Pictures = pictureViewModels,
                SortOrder = order,
                PageNumber = pageNumber,
                CountOfPages = pager.GetCountOfPages()
            };
            ViewBag.UserId = userId;

            return PartialView(model);
        }

        public async Task<IActionResult> UsersList()
        {
            if (User.IsInRole("admin"))
            {
                return RedirectToAction("UsersListForAdmin");
            }

            ICollection<User> users = await _userServices.GetAllAsync();
            List<UserViewModel> usersList = new List<UserViewModel>();

            foreach(var user in users)
            {
                UserViewModel model = Mapper.Map<User, UserViewModel>(user);
                usersList.Add(model);
            }

            return View(usersList);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UsersListForAdmin()
        {
            ICollection<User> users = await _userServices.GetAllAsync();
            List<UserViewModel> usersList = new List<UserViewModel>();

            foreach (var user in users)
            {
                UserViewModel model = Mapper.Map<User, UserViewModel>(user);
                model.IsLockedOut = await _userServices.IsLockedOutAsync(user);
                usersList.Add(model);
            }

            return View(usersList);
        }

        public async Task<IActionResult> Profile(Guid id)
        {
            User user = await _userServices.FindByIdAsync(id);
            UserViewModel userViewModel = Mapper.Map<User, UserViewModel>(user);

            List<Picture> userPictures = new List<Picture>();
            foreach (var album in userViewModel.Albums)
            {
                userPictures.AddRange(album.Pictures);
            }

            int pageNumber = 1;
            PictureSortState sortOrder = PictureSortState.PostDateTimeDesc;
            PictureSorter sorter = new PictureSorter
            {
                Pictures = userPictures.AsQueryable(),
                SortOrder = sortOrder
            };

            Pager<Picture> pager = new Pager<Picture>();
            pager.SetRecordsOnPage(_picturesOnPage);
            pager.SetRecords(sorter.Sort().ToList());

            List<PictureViewModel> pictureViewModels = Mapper.Map<IList<Picture>, List<PictureViewModel>>(pager.GetPage(pageNumber));
            foreach (var picture in pictureViewModels)
            {
                picture.ThumbnailRelativePath = _pictureServices.GetThumbnailRelativePath(await _pictureServices.GetAsync(picture.Id));
            }

            PictureSearchViewModel pictureSearchViewModel = new PictureSearchViewModel
            {
                PageNumber = 1,
                Pictures = pictureViewModels,
                SortOrder = sortOrder,
                CountOfPages = pager.GetCountOfPages()
            };

            userViewModel.PictureSearchViewModel = pictureSearchViewModel;
            ViewBag.UserId = id;

            return View(userViewModel);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            User user = await _userServices.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            if (!(await IsAdminOrCurrentUser(user)))
            {
                return StatusCode(401);
            }
            EditUserViewModel editModel = Mapper.Map<User, EditUserViewModel>(user);
            return View(editModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userServices.FindByIdAsync(model.Id);
                if (!(await IsAdminOrCurrentUser(user)))
                {
                    return StatusCode(401);
                }
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Pseudonym = model.Pseudonym;
                user.Email = model.Email;
                user.Address = model.Address;
                user.UserName = model.Email;

                var result = await _userServices.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("UsersList");
                }
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            User user = await _userServices.FindByIdAsync(id);
            if (!await IsAdminOrCurrentUser(user))
            {
                return StatusCode(401);
            }
            if (user != null)
            {
                await _signInServices.SignOutAsync();
                await _userServices.DeleteAsync(user);
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> LockUser(Guid id)
        {
            User user = await _userServices.FindByIdAsync(id);
            LockUserViewModel lockUserViewModel = Mapper.Map<User, LockUserViewModel>(user);
            return View(lockUserViewModel);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> LockUser(LockUserViewModel lockUserViewModel)
        {
            User user = await _userServices.FindByIdAsync(lockUserViewModel.Id);
            if (user != null)
            {
                var result = await _userServices.SetLockOutEnabledAsync(user, true);
                if (result.Succeeded)
                {
                    user.BlockReason = lockUserViewModel.BlockReason;
                    await _userServices.UpdateAsync(user);
                    await _userServices.SetLockOutEndDateAsync(user, DateTimeOffset.MaxValue);
                }
            }
            return RedirectToAction("UsersList");
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> UnlockUser(Guid id)
        {
            User user = await _userServices.FindByIdAsync(id);
            if (user != null)
            {
                user.BlockReason = string.Empty;
                await _userServices.UpdateAsync(user);
                await _userServices.ResetAccessFailedCountAsync(user);
                await _userServices.SetLockOutEndDateAsync(user, DateTimeOffset.MinValue);
            }
            return RedirectToAction("UsersList");
        }

        public async Task<IActionResult> ChangePassword(Guid id, string message = null)
        {
            User user = await _userServices.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            if (!(await IsCurrentUser(user)))
            {

Gallery/Views/Picture/AddPicture.cshtml
@model Gallery.Models.PictureViewModels.AddingPictureViewModel

@{
    ViewData["Title"] = "Adding picture";
}

<h2>AddPicture</h2>

<h4>Adding picture</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPicture" asp-controller="Picture" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="AlbumId" />
            </div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" type="file" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Load" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-controller="Album" asp-action="Album" asp-route-albumId=@Model.AlbumId>Back to album</a>
</div>

Gallery/Views/Picture/DeletePictureForReason.cshtml
@model Gallery.Models.PictureViewModels.PictureViewModel
@{
    ViewData["Title"] = "Delete picture";
}

<h2>Delete picture</h2>

<div class="form-group">
    <img src="@Url.Content(Model.RelativePath)">
</div>

<form asp-controller="Picture" asp-action="DeletePictureForReason" method="post">
    <div class="form-group">
        <input type="hidden" name="pictureId" value="@Model.Id" />
    </div>

    <div class="form-group">
        <input type="text" name="reason" class="form-control" />
    </div>
    <button type="submit" class="btn btn-default">Delete</button>
</form>

Gallery/Views/Picture/ViewPictureInFullSize.cshtml
@model Gallery.Models.PictureViewModels.PictureViewModel
@{
    ViewData["Title"] = Model.Name;
}

<script src="~/js/signalr.min.js"></script>


<div id="deletePictureDialog" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Delete picture</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure want to delete this picture?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" onclick="deletePicture()">Yes</button>
            </div>
        </div>
    </div>
</div>

<div id="deletePictureForReasonDialog" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Delete picture</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure want to delete this picture?</p>
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="deletePictureReason">Reason</label>
                    <div class="col-sm-7">
                        <input type="text" id="deletePictureReason" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" onclick="deletePictureForReason()">Yes</button>
            </div>
        </div>
    </div>
</div>


<div class="form-group">
    <h3>
        <a asp-controller="Users" asp-action="Profile" asp-route-id="@Model.UserId">@ViewBag.OwnerPseudonym</a>
    </h3>
    <h3>
        <a asp-controller="Album" asp-action="Album" asp-route-albumId="@Model.Album.Id">@Model.Album.Name</a>
    </h3>
</div>

<div class="form-group">
    <img src="@Url.Content(Model.RelativePath)">

    <div class="container">
        <div class="row">
            <div class="col-sm-1">
                <button type="submit" class="btn btn-sm btn-primary" onclick="changeRating()">
                    <div id="rating">@Model.Ratings.Count likes</div>
                </button>

            </div>
            <div class="col-sm-1">
                @if (ViewBag.UserIsAuthenticated)
                {
                    if (User.IsInRole("admin"))
                    {
                        <button class="btn btn-danger" onclick="showDeletePictureForReasonDialog()">Delete picture</button>
                    }
                    if (ViewBag.CurrentUserId == Model.UserId)
                    {
                        <button class="btn btn-danger" onclick="showDeletePictureDialog()">Delete picture</button>
                    }
                }
            </div>
        </div>
    </div>
</div>

<div class="form-group">
    @foreach (var tag in Model.TagNames)
    {
        <a class="btn btn-sm btn-default" asp-controller="Search" asp-action="Index" asp-route-searchExpression="@tag">@tag</a>
    }
</div>

<div class="form-group">
    <h2>@Model.Name</h2>
    <h3>@Model.Description</h3>
</div>

<a class="btn btn-default" asp-controller="Picture" asp-action="ViewPictureInFullSize" asp-route-pictureId="@ViewBag.PreviousPictureId">Previous picture</a>
<a class="btn btn-default" asp-controller="Picture" asp-action="ViewPictureInFullSize" asp-route-pictureId="@ViewBag.NextPictureId">Next picture</a>
<br />


@await Html.PartialAsync("~/Views/Comment/GetComments.cshtml", Model)

<script>
    let ratingHubConnection = new signalR.HubConnection("/RatingHub", { useDefaultPath: false });
    let commentHubConnection = new signalR.HubConnection("/CommentHub", { useDefaultPath: false });

    ratingHubConnection.on("Send", function () {
        updateRating();
    });

    commentHubConnection.on("Send", function () {
        updateComments();
    });

    function updateRating() {
        $.ajax({
            type: 'GET',
            url: '/Picture/GetPictureRating',
            data: {
                "pictureId": "@Model.Id"
            },
            dataType: 'json',
            success: function (data) {
                if (data != null) {
                    $("#rating").replaceWith("<div id=\"rating\">" + data["value"] + " likes" + "</div>");
                }
            }
        });
    }

    function changeRating() {
        $.ajax({
            type: 'POST',
            url: '/Rating/ChangeRating',
            data: {
                "pictureId": "@Model.Id"
            },
            dataType: 'json',
            success: function (data) {
                if (data != null) {
                    ratingHubConnection.invoke("Send");
                }
            }
        });
    }


    function updateComments() {
        $.ajax({
            type: 'GET',
            url: '/Comment/GetComments',
            data: {
                "pictureId": "@Model.Id"
            },
            dataType: 'html',
            success: function (data) {
                if (data != null) {
                    $("#comments").replaceWith(data);
                }
            }
        });
    }

    function deleteComment(data) {
        $.ajax({
            type: 'POST',
            url: '/Comment/DeleteComment',
            data: {
                'commentId': data
            },
            success: function() {
                commentHubConnection.invoke("Send");
            }
        });
    }

    function addComment() {
        let comment = document.getElementById("message").value;
        $.ajax({
            type: 'POST',
            url: '/Comment/AddComment',
            data: {
                'pictureId': "@Model.Id",
                'commentText': comment
            },
            success: function () {
                commentHubConnection.invoke("Send");
            }
        });
    }


    ratingHubConnection.start();
    commentHubConnection.start();

</script>



@if (ViewBag.UserIsAuthenticated && ViewBag.CurrentUserId == Model.UserId)
{
    <script>
        function showDeletePictureDialog() {
            $("#deletePictureDialog").modal('show');
        }

        function deletePicture() {
            $.ajax({
                type: 'POST',
                url: '/Picture/DeletePicture',
                data: {
                    'pictureId': "@Model.Id"
                },
                dataType: 'html',
                success: function() {
                    window.location.replace("/Album/Album?albumId=@Model.Album.Id");
                }
            });
        }
    </script>
}



@if (ViewBag.UserIsAuthenticated && User.IsInRole("admin"))
{
    <script>
        function showDeletePictureForReasonDialog() {
            $("#deletePictureForReasonDialog").modal('show');
        }

        function deletePictureForReason() {
            $.ajax({
                type: 'POST',
                url: '/Picture/DeletePictureForReason',
                data: {
                    'pictureId': "@Model.Id",
                    'reason': document.getElementById('deletePictureReason').value
                },
                dataType: 'html',
                success: function() {
                    window.location.replace("/Album/Album?albumId=@Model.Album.Id");
                }
            });
        }
    </script>
}