Gallery/Models/UserManagingViewModels/ChangePasswordViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Gallery.Models.UserManagingViewModels
{
    public class ChangePasswordViewModel
    {
        public Guid Id { get; set; }

        public string Email { get; set; }

        [Display(Name = "Old password")]
        public string OldPassword { get; set; }
        [Display(Name = "New password")]
        public string NewPassword { get; set; }
    }
}

Gallery/Models/UserManagingViewModels/LockUserViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Gallery.Models.UserManagingViewModels
{
    public class LockUserViewModel
    {
        [Required]
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Pseudonym { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }

        [Display(Name = "Block reason")]
        public string BlockReason { get; set; }
    }
}

Gallery/Models/UserManagingViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Gallery.Models.PictureViewModels;
using GalleryStorage.Models;

namespace Gallery.Models.UserManagingViewModels
{
    public class UserViewModel
    {
        public Guid Id { get; set; }

        [Display(Name = "First name")]
        public string FirstName { get; set; }
        [Display(Name = "Last name")]
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Pseudonym { get; set; }

        public string Email { get; set; }
        public string Address { get; set; }

        [Display(Name = "Is locked out")]
        public bool IsLockedOut { get; set; }
        [Display(Name = "Block reason")]
        public string BlockReason { get; set; }

        public ICollection<string> UserRoles { get; set; }
        public virtual IList<Album> Albums { get; set; }
        public PictureSearchViewModel PictureSearchViewModel { get; set; }
    }
}

Gallery/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Gallery.Models.RolesManagingViewModels;
using GalleryServices.ServicesInterfaces;
using GalleryStorage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace Gallery.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        private readonly IUserServices<User> _userServices;
        private readonly IRoleServices<Role> _roleServices;

        public RolesController(IUserServices<User> userServices, IRoleServices<Role> roleServices)
        {
            _userServices = userServices;
            _roleServices = roleServices;
        }
        
        public async Task<IActionResult> Edit(Guid id)
        {
            User user = await _userServices.FindByIdAsync(id);
            if (user != null)
            {
                var userRoles = await _userServices.GetRolesAsync(user);
                var allRoles = _roleServices.GetAll();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles.ToList()
                };
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, List<string> roles)
        {
            User user = await _userServices.FindByIdAsync(id);
            if (user != null)
            {
                var userRoles = await _userServices.GetRolesAsync(user);
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _userServices.AddToRolesAsync(user, addedRoles);
                await _userServices.RemoveFromRolesAsync(user, removedRoles);
                return RedirectToAction("UsersList", "Users");
            }

            return NotFound();
        }
    }
}

Gallery/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using Gallery.Models.PictureViewModels;
using GalleryStorage.Models;
using Gallery.Models.UserManagingViewModels;
using Gallery.Sorting;
using Gallery.Pager;
using GalleryServices.ServicesInterfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;

namespace Gallery.Controllers
{
    public class UsersController : BaseController
    {
        private readonly IConfiguration _configuration;
        private readonly ISignInServices<User> _signInServices;
        private readonly IPictureServices<Picture> _pictureServices;
        private readonly int _picturesOnPage;

        public UsersController(IConfiguration configuration, IUserServices<User> userServices, ISignInServices<User> signInServices, IPictureServices<Picture> pictureServices)
            : base(userServices)
        {
            _configuration = configuration;
            _picturesOnPage = Int32.TryParse(_configuration["PicturesOnPage:Default"], out _picturesOnPage) ? Int32.Parse(_configuration["PicturesOnPage:Default"]) : 16;
            _userServices = userServices;
            _signInServices = signInServices;
            _pictureServices = pictureServices;
        }


        public async Task<IActionResult> GetUserPicturesPage(Guid userId, int? page, PictureSortState? sortOrder)
        {
            User user = await _userServices.FindByIdAsync(userId);
            List<Picture> userPictures = new List<Picture>();
            foreach (var album in user.Albums)
            {
                userPictures.AddRange(album.Pictures);
            }

            int pageNumber = page ?? 1;
            if (pageNumber == 0)
            {
                pageNumber = 1;
            }
            PictureSortState order = sortOrder ?? PictureSortState.PostDateTimeDesc;

            PictureSorter sorter = new PictureSorter
            {
                Pictures = userPictures.AsQueryable(),
                SortOrder = order
            };

            Pager<Picture> pager = new Pager<Picture>();
            pager.SetRecordsOnPage(_picturesOnPage);
            var picturesForPager = sorter.Sort().ToList();
            pager.SetRecords(picturesForPager);

            List<PictureViewModel> pictureViewModels = new List<PictureViewModel>();
            foreach (var picture in pager.GetPage(pageNumber))
            {
                PictureViewModel pictureViewModel = Mapper.Map<Picture, PictureViewModel>(picture);
                pictureViewModel.ThumbnailRelativePath = _pictureServices.GetThumbnailRelativePath(await _pictureServices.GetAsync(picture.Id));
                pictureViewModels.Add(pictureViewModel);
            }

            PictureSearchViewModel model = new PictureSearchViewModel
            {
                Pictures = pictureViewModels,
                SortOrder = order,
                PageNumber = pageNumber,
                CountOfPages = pager.GetCountOfPages()
            };
            ViewBag.UserId = userId;

            return PartialView(model);
        }

        public async Task<IActionResult> UsersList()
        {
            if (User.IsInRole("admin"))
            {
                return RedirectToAction("UsersListForAdmin");
            }

            ICollection<User> users = await _userServices.GetAllAsync();
            List<UserViewModel> usersList = new List<UserViewModel>();

            foreach(var user in users)
            {
                UserViewModel model = Mapper.Map<User, UserViewModel>(user);
                usersList.Add(model);
            }

            return View(usersList);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UsersListForAdmin()
        {
            ICollection<User> users = await _userServices.GetAllAsync();
            List<UserViewModel> usersList = new List<UserViewModel>();

            foreach (var user in users)
            {
                UserViewModel model = Mapper.Map<User, UserViewModel>(user);
                model.IsLockedOut = await _userServices.IsLockedOutAsync(user);
                usersList.Add(model);
            }

            return View(usersList);
        }

        public async Task<IActionResult> Profile(Guid id)
        {
            User user = await _userServices.FindByIdAsync(id);
            UserViewModel userViewModel = Mapper.Map<User, UserViewModel>(user);

            List<Picture> userPictures = new List<Picture>();
            foreach (var album in userViewModel.Albums)
            {
                userPictures.AddRange(album.Pictures);
            }

            int pageNumber = 1;
            PictureSortState sortOrder = PictureSortState.PostDateTimeDesc;
            PictureSorter sorter = new PictureSorter
            {
                Pictures = userPictures.AsQueryable(),
                SortOrder = sortOrder
            };

            Pager<Picture> pager = new Pager<Picture>();
            pager.SetRecordsOnPage(_picturesOnPage);
            pager.SetRecords(sorter.Sort().ToList());

            List<PictureViewModel> pictureViewModels = Mapper.Map<IList<Picture>, List<PictureViewModel>>(pager.GetPage(pageNumber));
            foreach (var picture in pictureViewModels)
            {
                picture.ThumbnailRelativePath = _pictureServices.GetThumbnailRelativePath(await _pictureServices.GetAsync(picture.Id));
            }

            PictureSearchViewModel pictureSearchViewModel = new PictureSearchViewModel
            {
                PageNumber = 1,
                Pictures = pictureViewModels,
                SortOrder = sortOrder,
                CountOfPages = pager.GetCountOfPages()
            };

            userViewModel.PictureSearchViewModel = pictureSearchViewModel;
            ViewBag.UserId = id;

            return View(userViewModel);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            User user = await _userServices.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            if (!(await IsAdminOrCurrentUser(user)))
            {
                return StatusCode(401);
            }
            EditUserViewModel editModel = Mapper.Map<User, EditUserViewModel>(user);
            return View(editModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userServices.FindByIdAsync(model.Id);
                if (!(await IsAdminOrCurrentUser(user)))
                {
                    return StatusCode(401);
                }
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Pseudonym = model.Pseudonym;
                user.Email = model.Email;
                user.Address = model.Address;
                user.UserName = model.Email;

                var result = await _userServices.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("UsersList");
                }
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            User user = await _userServices.FindByIdAsync(id);
            if (!await IsAdminOrCurrentUser(user))
            {
                return StatusCode(401);
            }
            if (user != null)
            {
                await _signInServices.SignOutAsync();
                await _userServices.DeleteAsync(user);
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> LockUser(Guid id)
        {
            User user = await _userServices.FindByIdAsync(id);
            LockUserViewModel lockUserViewModel = Mapper.Map<User, LockUserViewModel>(user);
            return View(lockUserViewModel);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> LockUser(LockUserViewModel lockUserViewModel)
        {
            User user = await _userServices.FindByIdAsync(lockUserViewModel.Id);
            if (user != null)
            {
                var result = await _userServices.SetLockOutEnabledAsync(user, true);
                if (result.Succeeded)
                {
                    user.BlockReason = lockUserViewModel.BlockReason;
                    await _userServices.UpdateAsync(user);
                    await _userServices.SetLockOutEndDateAsync(user, DateTimeOffset.MaxValue);
                }
            }
            return RedirectToAction("UsersList");
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> UnlockUser(Guid id)
        {
            User user = await _userServices.FindByIdAsync(id);
            if (user != null)
            {
                user.BlockReason = string.Empty;
                await _userServices.UpdateAsync(user);
                await _userServices.ResetAccessFailedCountAsync(user);
                await _userServices.SetLockOutEndDateAsync(user, DateTimeOffset.MinValue);
            }
            return RedirectToAction("UsersList");
        }

        public async Task<IActionResult> ChangePassword(Guid id, string message = null)
        {
            User user = await _userServices.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            if (!(await IsCurrentUser(user)))
            {

Gallery/Views/Users/ChangePassword.cshtml
@model  Gallery.Models.UserManagingViewModels.ChangePasswordViewModel
@{
    ViewData["Title"] = "ChangePassword";
}

<h2>Changing password for @Model.Email</h2>
<form asp-action="ChangePassword" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="Email" />
    
    @if (ViewBag.Message != null)
    {
        <p>@ViewBag.Message</p>
        <hr/>
    }
    
    <div class="form-group">
        <label asp-for="OldPassword" class="control-label">Current password</label>
        <input type="password" asp-for="OldPassword" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="NewPassword" class="control-label">New password</label>
        <input type="password" asp-for="NewPassword" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-default" />
        <a class="btn btn-primary" asp-controller="Users" asp-action="UsersList">Back</a>
    </div>
</form>

Gallery/Views/Users/Edit.cshtml
@model  Gallery.Models.UserManagingViewModels.EditUserViewModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>
<form asp-controller="Users" asp-action="Edit">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="form-group">
        <label asp-for="FirstName" class="control-label"></label><br />
        <input type="text" asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="control-label"></label><br />
        <input type="text" asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName"></span>
    </div>
    <div class="form-group">
        <label asp-for="Pseudonym" class="control-label"></label><br />
        <input type="text" asp-for="Pseudonym" class="form-control" />
        <span asp-validation-for="Pseudonym"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label><br />
        <input type="text" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address" class="control-label"></label><br />
        <input type="text" asp-for="Address" class="form-control" />
        <span asp-validation-for="Address"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-default" />
        <a class="btn btn-primary" asp-controller="Home" asp-action="PersonalArea">Back</a>
    </div>
</form>

Gallery/Views/Users/GetUserPicturesPage.cshtml
@model Gallery.Models.PictureViewModels.PictureSearchViewModel

@foreach (var pic in Model.Pictures)
{
    <a asp-controller="Picture" asp-action="ViewPictureInFullSize" asp-route-pictureId="@pic.Id">
        <img src="@Url.Content(pic.ThumbnailRelativePath)">
    </a>
}

Gallery/Views/Users/LockUser.cshtml
@model Gallery.Models.UserManagingViewModels.LockUserViewModel
@{
    ViewData["Title"] = "Lock User";
}

<h2>Lock User @Model.FirstName @Model.LastName</h2>
<form asp-controller="Users" asp-action="LockUser">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="BlockReason" class="control-label">Block reason</label>
        <input type="text" asp-for="BlockReason" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Block user" class="btn btn-danger" />
        <a class="btn btn-primary" asp-controller="Users" asp-action="UsersList">Back</a>
    </div>
</form>

Gallery/Views/Users/Profile.cshtml
@model Gallery.Models.UserManagingViewModels.UserViewModel
@{
    ViewData["Title"] = "Profile";
}

<h2>@Model.Pseudonym profile</h2>

@foreach (var album in Model.Albums)
{
    <a class="btn btn-default" asp-controller="Album" asp-action="Album" asp-route-albumId="@album.Id">@album.Name</a><br />
}
<hr/>

<button id="SortByTime" type="button" class="btn btn-sm btn-default" onclick="SortByTime()">Post time</button>
<button id="SortByRating" type="button" class="btn btn-sm btn-default" onclick="SortByRating()">Likes</button>


<div id="page">@await Html.PartialAsync("GetUserPicturesPage", Model.PictureSearchViewModel)</div>

<div id="progress" style="display:none;">
    <img src="~/images/Spinner.gif" alt="Loading" /> Loading...
</div>
<div id="progressmarker"></div>


<script>
    var _incallback = false;
    var pageNumber = 2;
    var sortOrder = "PostDateTimeDesc";

    $(document).ready(function() {
        $(window).scroll(function() {
            var hT = $('#progressmarker').offset().top,
                hH = $('#progressmarker').outerHeight(),
                wH = $(window).height(),
                wS = $(window).scrollTop();
            if (@Model.PictureSearchViewModel.CountOfPages >= @Model.PictureSearchViewModel.PageNumber &&
                !_incallback) {
                if (wS > (hT + hH - wH)) {
                    GetPage();
                }
            }
        });
    });

    function SortByTime() {
        if (sortOrder === "PostDateTimeDesc") {
            sortOrder = "PostDateTimeAsc";
        } else {
            sortOrder = "PostDateTimeDesc";
        }
        $("#page").empty();
        pageNumber = 1;
        GetPage();
    }

    function SortByRating() {
        if (sortOrder === "RatingDesc") {
            sortOrder = "RatingAsc";
        } else {
            sortOrder = "RatingDesc";
        }
        pageNumber = 1;
        $("#page").empty();
        GetPage();
    }

    function GetPage() {
        _incallback = true;
        $.ajax({
            type: 'GET',
            url: '/Users/GetUserPicturesPage',
            data: {
                "userId": "@Model.Id",
                "page": pageNumber,
                "sortOrder": sortOrder
            },
            dataType: 'html',
            success: function (data) {
                if (data != null) {
                    $("#page").append(data);
                    pageNumber++;
                }
            },
            beforeSend: function () {
                $("#progress").show();
            },
            complete: function () {
                $("#progress").hide();
                _incallback = false;
            },
            error: function () {
                _incallback = false;
            }
        });
    }
</script>

Gallery/Views/Users/UsersList.cshtml
@model List<Gallery.Models.UserManagingViewModels.UserViewModel>

@{
    ViewData["Title"] = "Users";
}

<h2>Users</h2>

@foreach(var user in Model)
{
    if (!string.Equals(user.UserName, User.Identity.Name))
    {
        <form>
            <a class="btn btn-default" asp-controller="Users" asp-action="Profile" asp-route-id="@user.Id" method="get">@user.Pseudonym</a>
        </form>
    }
}
<br/>

<a class="btn btn-primary" asp-controller="Home" asp-action="Index">Back</a>

Gallery/Views/Users/UsersListForAdmin.cshtml
@model List<Gallery.Models.UserManagingViewModels.UserViewModel>

@{
    ViewData["Title"] = "Managing users";
}

<h2>Users</h2>

<table class="table-condensed">
    <tr>
        <th>Full Name</th>
        <th>Pseudonym</th>
        <th>Email</th>
        <th>Address</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.FirstName @user.LastName</td>
            <td>
                <form>
                    <a asp-controller="Users" asp-action="Profile" asp-route-id="@user.Id" method="get">@user.Pseudonym</a>
                </form>
            </td>
            <td>@user.Email</td>
            <td>@user.Address</td>
            @if (user.IsLockedOut)
            {
                <td>The user is locked</td>
            }
            else
            {
                <td>The user isn't locked</td>
            }
            <td>
                <form>
                    <a asp-controller="Users" asp-action="Edit" asp-route-id="@user.Id" class="btn btn-sm btn-primary">Edit</a>
                </form>
            </td>
            <td>
                <form>
                    <a asp-controller="Roles" asp-action="Edit" asp-route-id="@user.Id" class="btn btn-sm btn-primary">Rigths</a>
                </form>
            </td>
            <td>
                <a class="btn btn-sm btn-primary" asp-controller="Users" asp-action="ChangePassword" asp-route-id="@user.Id" method="get">Change password</a>
            </td>
            <td>
                <button id="ResetPassword" type="button" class="btn btn-sm btn-primary" onclick="ResetPassword('@user.Email')">Reset password</button>
            </td>
            <td>
                <form>
                    <a class="btn btn-sm btn-danger" asp-action="LockUser" asp-route-id="@user.Id">Lock</a>
                </form>
            </td>
            <td>
                <form asp-action="UnlockUser" asp-route-id="@user.Id" method="post">
                    <button type="submit" class="btn btn-sm btn-warning">Unlock</button>
                </form>
            </td>
            <td>
                <form asp-action="Delete" asp-route-id="@user.Id" method="post">
                    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>

<a class="btn btn-primary" asp-controller="Home" asp-action="Index">Back</a>


<script>
    function ResetPassword(email) {
        $.ajax({
            type: 'POST',
            url: '/Account/ForgotPassword',
            data: {
                "Email": email
            },
            dataType: 'html',
            success: function (data) {
                alert("Password reset");
            },
            error: function () {
                alert("error while password reset");
            }
        });
    }
</script>